### PR TITLE
tiltfile: make staticbuild helper (i.e. make image target assertions specific to the type of build)

### PR DESCRIPTION
**Pull request by maiamcc**
Hello @landism, @nicks,

Please review the following commits I made in branch maiamcc/static-build-helper:

bb2a3ca255fde5e0f8231ded904e736b45768b48 (2019-03-13 16:11:34 -0400)
tiltfile: make staticbuild helper (i.e. make image target assertions specific to the type of build)

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
i thought we were moving away from the StaticBuild terminology and towards the DockerBuild terminology? and this seems to move us in the wrong direction?

**Comment by maiamcc** [comment]
this PR isn't about the terminology as much as making the helper explicitly assert what kind of build it is (as opposed to just checking the fields common to staticBuild/fastBuild). I'm super down to rename this later, but i'd rather not do a big rename in the codebase before we've even phased out fastBuild in its current form.

**Comment by nicks** [comment]
ah, i'm confused, this pr does a big rename from db -> sb? why not just leave it as sb?

**Comment by maiamcc** [comment]
...oh. because we're asserting on the `staticBuild` struct, not the call to `docker_build` that created it.

**Comment by maiamcc** [comment]
...i'm rolling back most of this rename as part of a PR getting ready for LiveUpdate and i'm full of chagrin 😅

**Pull request merged**
