### PR TITLE
engine: s/building/updating in buildcontroller log

### PR DESCRIPTION
**Pull request by jazzdan**
Mostly a PR for discussion. Seems to make sense in all contexts right now. WDYT?

### CODE REVIEW

**Comment by jazzdan** [comment]
@dbentley ping on this, also adding @l-korbes as a reviewer

**Comment by l-korbes** [comment]
Copied from Slack:

> Most tools call it by two separate steps, building and deploying. Since we're merging the two into a general term we don't have to follow those, and IMO "updating" is clearer and more intuitive to end users.

So +1 here.

**Comment by hyu** [comment]
As part of my work on Update vs LiveUpdate, I'm adopting your proposed change, @jazzdan. (And also making some other changes to make this line appear differently in the Web UI.)

Do you mind closing this PR to avoid the possibly of mild merge conflicts?

**Comment by jazzdan** [comment]
You got it @hyu!

**Pull request closed without merging**
