### PR TITLE
hud: if showing logs inline, try crashLogs first [ch1090]

### PR DESCRIPTION
**Pull request by maiamcc**
Hello @nicks, @landism,

Please review the following commits I made in branch maiamcc/show-crash-log-first:

14508345a9d31328df387b80f629b67955034789 (2018-12-07 16:00:11 -0500)
hud: if showing logs inline, try crashLogs first [ch1090]

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
unit test?

**Comment by maiamcc** [comment]
yep on it now

**Comment by maiamcc** [comment]
To be clear, this doesn't differentiate between showing crash log vs. pod log according to whether we're crash rebuilding or not -- it's just an emergent property of this code that, since we don't set crash log UNLESS we're doing a crash rebuild, that we'll only show the crash log for cases where we would otherwise show stale logs.

something that programmatically does this would look like:
```
if isCrashing(v.res) {
		podLog := v.res.CrashLog
		// Show the current podLog inline if a. we don't have a crash log to show, or
		// b. if we're NOT CrashRebuilding -- i.e. we didn't replace the pod, so can
		// just show the most recent pod logs.
		if podLog == "" || !isCrashRebuilding(v.res) {
			podLog = v.res.PodLog
		}
    ...
}
```

would you rather this code be in there?

**Comment by nicks** [comment]
i'm not sure!

**Pull request merged**
