### PR TITLE
engine: don't push to a central registry when using docker-for-mac

### PR DESCRIPTION
**Pull request by nicks**
Hello @yuindustries, @jazzdan,

Please review the following commits I made in branch nicks/kube:

9e8ad19ed93c1ab1cb01932e2863d7840f708bcd (2018-08-17 18:18:15 -0400)
engine: don't push to a central registry when using docker-for-mac

### CODE REVIEW

**Comment by nicks** [comment]
i don't have a mac at work so will have to go home to test this :grimacing:

**Comment by jazzdan** [comment]
When I ran this on my Mac the service that it created appears to still be looking for the image in gcr

```
  Type     Reason                 Age               From                         Message
  ----     ------                 ----              ----                         -------
  Normal   Scheduled              21s               default-scheduler            Successfully assigned devel-dan-blorgly-be-cb997fc5f-827v8 to docker-for-desktop
  Normal   SuccessfulMountVolume  21s               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-jfcsc"
  Normal   BackOff                18s               kubelet, docker-for-desktop  Back-off pulling image "gcr.io/blorg-dev/blorgly-backend:devel-dan@sha256:c2fb1dff3e36beeec017ad9aa0861a10c79360276ced5befc2177934e94355d3"
  Warning  Failed                 18s               kubelet, docker-for-desktop  Error: ImagePullBackOff
  Normal   Pulling                3s (x2 over 20s)  kubelet, docker-for-desktop  pulling image "gcr.io/blorg-dev/blorgly-backend:devel-dan@sha256:c2fb1dff3e36beeec017ad9aa0861a10c79360276ced5befc2177934e94355d3"
  Warning  Failed                 2s (x2 over 20s)  kubelet, docker-for-desktop  Failed to pull image "gcr.io/blorg-dev/blorgly-backend:devel-dan@sha256:c2fb1dff3e36beeec017ad9aa0861a10c79360276ced5befc2177934e94355d3": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/blorg-dev/blorgly-backend@sha256:c2fb1dff3e36beeec017ad9aa0861a10c79360276ced5befc2177934e94355d3 not found
  Warning  Failed                 2s (x2 over 20s)  kubelet, docker-for-desktop  Error: ErrImagePull
```

**Comment by nicks** [comment]
hmmmm....that's weird...i'll poke at it some more tonight.

**Comment by nicks** [comment]
@jazzdan / @yuindustries ok, i think i know what the issue is, if you have time, can you try this again? if not, that's ok, i can try it with my home mac

**Comment by nicks** [comment]
ahhh, still not working, will debug more at home

**Pull request closed without merging**
