### PR TITLE
store: add optional SetUp method for subscribers

### PR DESCRIPTION
**Pull request by maiamcc**
Hello @nicks,

Please review the following commits I made in branch maiamcc/subscriber-setup:

2f2613ba1668f3acacf8a0c332dbf6c1fb54d52e (2019-04-30 14:33:55 -0400)
store: add optional SetUp method for subscribers

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by maiamcc** [comment]
Unsure if the behavior in the second commit is right, would love feedback.

**Comment by maiamcc** [comment]
...was trying to follow the naming conventions already there but it's maybe simpler to call `s.SetUp()` when on `Add(s)` and not call any individual `SetUp` methods during `subscriberList.SetUp()` -- objections?

**Comment by nicks** [comment]
makes sense to me!

**Comment by nicks** [comment]
not sure i really understand your last question

**Comment by maiamcc** [comment]
🤷‍♀ then whatever, i'll leave it as is! i don't feel strongly

**Pull request merged**
