### PR TITLE
watch: record which dirs are watched in expvars

### PR DESCRIPTION
**Pull request by jazzdan**
To help diagnose #1817

Do we think that this will cause memory issues if it's enabled for everyone?

### CODE REVIEW

**Comment by nicks** [comment]
hmmmmm...have you been able to reproduce the problem locally? have you tried setting up a local Rust project in Tilt yet?

adding these kinds of metrics seems like a last-resort after other routes have been exhausted

**Comment by jazzdan** [comment]
@nicks haven't tried with Rust, no. Will do.

**Comment by jazzdan** [comment]
Closing because I have a repro case now, described in #1817

**Comment by nicks** [comment]
:clap:

**Pull request closed without merging**
