### PR TITLE
integration test checks if we can do live updates after a crash rebuild (currently fails)

### PR DESCRIPTION
**Pull request by maiamcc**
PR to run tests

### CODE REVIEW

**Comment by maiamcc** [comment]
Still have a unit test to write, but, does this look right?

**Comment by nicks** [comment]
no, this doesn't seem like the right change to me.

why is unioning with the old builds the right move?

**Comment by maiamcc** [comment]
Ah whoops, I forgot you didn't have context here.

We use that set of pod template spec hashes to check that incoming pod events are actually from pods that Tilt cares about. We do this filtering in the watcher code, so pod events that don't match a hash in this set don't even make it into `handlePodChangeAction`.

If we OVERWRITE the set of `PodTemplateSpecHashes` that we know about on every deploy, events from old pods (that Tilt DID deploy, but just isn't currently managing) won't ever hit `handlePodChangeAction` -- most importantly, we'll never catch the Pod Deleted actions for these old pods, which means we won't take them off the manifest, which means we'll always think we have too many pods to do a Live Update. Make sense?

**Comment by nicks** [comment]
Hmmmm...but why even wait until we get the pod deleted actions? we know the
old pods are old, so we can remove them right now?

**Comment by nicks** [comment]
alternatively, maybe the UIDs and PodTemplateSpecHashes should be part of some sort of a BuildHistory-like struct, so we can distinguish between what's old and what's current?

The fundamental mistake here (as I see it, given how i've seen this play out with other build systems), is that you're wiping out important context about the state (the old code threw out the old hashes, and the new code throws out which build they came from)

**Comment by maiamcc** [comment]
After discussion IRL, this PR doesn't accomplish what we want it to -- but @landism, you should probably add this updated integration test when you revert `PodTemplateSpecHash` stuff to make sure that LiveUpdate works properly after a crash rebuild.

**Pull request closed without merging**
