### PR TITLE
cli: add -f short flag for --file

### PR DESCRIPTION
**Pull request by nicks**
Hello @landism, @maiamcc,

Please review the following commits I made in branch nicks/file:

124942e3abd23273fa8d92029df0374222a5fe50 (2020-04-02 19:25:57 -0400)
cli: add -f short flag for --file

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
(this was bothering me, because it's a pretty common convention across tools in this space)

**Comment by victorwuky** [comment]
@nicks : I see `--file` being used in all these places. Does this mean `-f` can be used instead? If yes, can we add it to the docs. I'm happy to do it if you show me how. (I think the CLI docs are auto-generated?)

- https://docs.tilt.dev/cli/tilt.html
- https://docs.tilt.dev/cli/tilt_ci.html
- https://docs.tilt.dev/cli/tilt_docker-prune.html

**Comment by nicks** [comment]
@victorwuky yep, there's already a PR out for it!

**Comment by nicks** [comment]
https://github.com/windmilleng/tilt.build/pull/512

**Comment by victorwuky** [comment]
Thanks @nicks . Same concern as https://github.com/windmilleng/tilt/pull/3171#issuecomment-612046145 for context.

**Pull request merged**
