### PR TITLE
k8s: Treat kind as a local cluster

### PR DESCRIPTION
**Pull request by rohansingh**
Treat `kind` clusters as a local environment, just like minikube,
microk8s, etc.

### CODE REVIEW

**Comment by rohansingh** [comment]
This might not be worth merging if #1314 is going to solve the problem in a better way. But it works for now.

**Comment by jazzdan** [comment]
Hey @rohansingh I think this PR might be subsumed by my work in https://github.com/windmilleng/tilt/pull/1333, but I'm going to leave it open until I confirm with you that it is after I merge it. :)

**Comment by jazzdan** [comment]
(Also don't worry about integration test failures, external PRs can't run them for some reason 🙄 )

**Comment by rohansingh** [comment]
Obsoleted by #1333.

**Pull request closed without merging**
