### PR TITLE
tiltfile: add network argument to docker_buld

### PR DESCRIPTION
**Pull request by detiber**
- Adds a network argument to the docker_build command
- Plumbs the network argument in docker_build through to the underlying docker build

Fixes: #2483

### CODE REVIEW

**Comment by detiber** [comment]
Need to rework my local dev environment a bit to replicate the test failure from CI. Does anyone have any tips on how to get the config needed for using go modules with a vendor directory when using Goland as an IDE?

**Comment by nicks** [comment]
i think the test failure might be spurious, re-running it now

**Comment by nicks** [comment]
yup it passed! :smile:

**Comment by nicks** [comment]
LGTM! The PR title is marked [wip], is there anything you wanted to do before we merge?

**Comment by detiber** [comment]
@nicks replicating/resolving the test failure was the main thing, removed the [WIP]

**Pull request merged**
