### PR TITLE
tiltfile: error if local_git_repo isn't a git repo

### PR DESCRIPTION
**Pull request by jazzdan**

### CODE REVIEW

**Comment by jazzdan** [comment]
I'm going to add a test for the error case.

**Comment by nicks** [comment]
will servantes break if you commit this?

**Comment by jazzdan** [comment]
I think so, yes. A pre-req for merging this will be https://app.clubhouse.io/windmill/story/110/selectively-mounting-files-in-a-container (so obviously I won't until that's in)

**Comment by nicks** [comment]
ya, i think that's a blocker before we can consider this

**Comment by jazzdan** [comment]
I rolled this in to a different PR.

**Pull request closed without merging**
