### PR TITLE
web: add two-level secondary nav

### PR DESCRIPTION
**Pull request by nicks**
Hello @hyu,

Please review the following commits I made in branch nicks/traceviewtabs:

4832a19b843009bfed41a6c9343ec487f5b2f15f (2020-02-28 19:39:31 -0500)
web: add two-level secondary nav

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
Screenshot from 2020-02-28 19-41-47

**Comment by nicks** [comment]
Currently there's no way to get to this in the UI without knowing the magic URL to navigate to it. Trying to add an extra level of navigational hierarchy without it getting too imposing.

**Comment by nicks** [comment]
Screenshot from 2020-03-06 16-56-26

**Comment by nicks** [comment]
I tweaked your mock a bit and tried to get things to line up a bit better. how's that?

also noticed that we lost the box-shadow somehow, so sent a separate PR: https://github.com/windmilleng/tilt/pull/3052

**Comment by nicks** [comment]
a way to play with this locally is run `tilt up` in tilt.build and go to http://localhost:10350/r/tilt-site/trace/build:1

**Comment by hyu** [comment]
Also: I myself understand what "For Update" means because I have a lot of contxt, but when you get this in front of other people for testing, please take note of whether they understand that label. I could see it being misleading or confusing. (i.e., if they don't make the connection that "update" refers to each successive "build"...and instead associate it with something like "upgrade." Who knows! ¯\_(ツ)_/¯)

**Comment by nicks** [comment]
new screenshots!

Screenshot from 2020-03-13 19-52-18
Screenshot from 2020-03-13 19-51-12

re: "For Update" - ya, I think it's a good question. I don't know! Will be listening carefully to whether people feel confused / disoriented, and how they describe this pane

**Pull request merged**
