### PR TITLE
allow extra time for OS to free bind address after IsBindAddrFree check

### PR DESCRIPTION
**Pull request by andymartin-sch**
See #2861 for more info.

This is a kludgy workaround -- I was still able to reproduce the underlying issue after sleeping for 10ms but have not seen it in ~2k `tilt up` executions after bumping the sleep time up to 100ms.

Some other options might be:
- to add the sleep directly to `IsBindAddrFree` [here](https://github.com/windmilleng/tilt/blob/8ea4b95e0f1fb39203faa2e95537337a211c19a5/internal/network/port.go#L25)
- eliminating all uses of `IsBindAddrFree` and always gracefully catching/handling the "address already in use" errors instead

No worries at all if you'd like to go with one of the above approaches (or something else entirely) instead of this PR.

### CODE REVIEW

**Comment by andymartin-sch** [comment]
I'm going to hold off messing around with debugging the issue with the CircleCI test until I hear whether or not this is the approach you all want to go with

**Comment by jazzdan** [comment]
Hey @andymartin-sch, don't worry about the integration test failure, they don't pass when kicked off by people outside of our org.

**Comment by jazzdan** [comment]
^ scratch that, apparently my information is outdated

**Comment by nicks** [comment]
The integration test failure is semi-legitimate. 

Basically, your change delays the server initialization.

tilt_args_test.go has a race condition because it doesn't wait for server initialization. That's a bug we should fix (see https://github.com/windmilleng/tilt/pull/2867). The race was unlikely to happen before, but with your change it happens more often.

**Comment by andymartin-sch** [comment]
Got it. That was my guess but I wasn't sure. Thanks for confirming!

**Comment by nicks** [comment]
ok, the integration test fix is in, but i think you need to rebase your changes on top of it

i also liked your suggestion of removing IsBindAddrFree and just handing the "address already in use" errors instead, so you could also wait on https://github.com/windmilleng/tilt/pull/2874

A lot of the network.IsBindAddrFree code is leftover from the days when we didn't have good internal APIs for shutting down Tilt gracefully, so the code for listening the code for error-handling lived in different places.

**Comment by andymartin-sch** [comment]
Yeah I think https://github.com/windmilleng/tilt/pull/2874 looks like a better solution than this PR - will leave it open for you all to decide but I'm totally in favor of going with that one instead.

Thank you for looking into this so quickly!

**Comment by andymartin-sch** [comment]
I verified #2874 resolves the underlying issue (#2861) and left some details in [this comment](https://github.com/windmilleng/tilt/issues/2861#issuecomment-579946982).

Going to close this out - thanks again!

**Pull request closed without merging**
